server:
  port: 8080
spring:
  application:
    name: partner
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.c31ujhjy02ba.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=weeklycoffee
    username: postgre
    password: password123!
  jpa:
    show-sql: true
    generate-ddl: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: amqps://b-2c76102e-2ad9-459d-b4f8-9656a169070f.mq.ap-northeast-2.amazonaws.com:5671
    username: rabbitmq
    password: password123!
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

---
#spring:
#  profiles: dev
#eureka:
#  client:
#    service-url:
#      defaultZone: http://ec2-3-34-216-213.ap-northeast-2.compute.amazonaws.com:8761/eureka/
#  instance:
#    hostname: ec2-3-34-216-213.ap-northeast-2.compute.amazonaws.com


